name: Tag Monthly GTN Release

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 1 * *'

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'
      - name: Tag it
        run: |
          python -m pip install --upgrade pip
          pip install requests
          python bin/make_release.py